# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Запуск АТ проекта inno_itog_project

on:
  push:
    branches: [ "main" ]
 
jobs:
  example_matrix:
    strategy:
      matrix:
        version: [ '17', '21', '23' ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.version }}
        distribution: 'temurin'
        cache: maven
    - name: Run test
      run: mvn clean test

    - name: Загружать историю отчетов о тестировании
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: https://github.com/Bgalina86/inno_itog_project.git
        path: src/test/resources/Allure_report

    - name: Создавать отчет о тестировании
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
          gh_pages: src/test/resources/Allure_report
          allure_history: allure-report
          allure_results: allure-results

#    - name: Публиковать отчет о тестировании
#      uses: peaceiris/actions-gh-pages@v3
#      if: always()
#      with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_branch: https://github.com/Bgalina86/inno_itog_project.git
#          publish_dir: allure-results

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
   # - name: Update dependency graph
   #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
